{% set oot_name = "sdrplay3" %}
{% set name = "gnuradio-" + oot_name %}
# Set package version from cleaned up git tags if possible,
# otherwise fall back to date-based version.
{% set tag_version = environ.get("GIT_DESCRIBE_TAG", "")|string|replace("-","_")|replace("v","")|replace("git","") %}
{% set post_commit = environ.get("GIT_DESCRIBE_NUMBER", 0)|string %}
{% set hash = environ.get("GIT_DESCRIBE_HASH", "local")|string %}
{% set fallback_version = "0.0.0.{0}.dev+g{1}".format(datetime.datetime.now().strftime("%Y%m%d"), environ.get("GIT_FULL_HASH", "local")[:9]) %}
{% set version = (tag_version if post_commit == "0" else "{0}.post{1}+{2}".format(tag_version, post_commit, hash)) if tag_version else fallback_version %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # use local path or git repository depending on if the build is local or done on CI
  path: "../.."  # [not os.environ.get("CI")]
  git_url: {{ environ.get('FEEDSTOCK_ROOT', "../..") }}  # [os.environ.get("CI")]

build:
  number: 0
  missing_dso_whitelist:
    - "*/sdrplay_api.dll"  # [win]
  ignore_run_exports:
    - gnuradio-pmt
    - ucrt
    - vc14_runtime

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - git
    - ninja
    - pkg-config
    # cross-compilation requirements
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - pybind11                            # [build_platform != target_platform]

  host:
    - gmp  # [linux]
    # the following two entries are for generating builds against specific GR versions
    - gnuradio-core  # [not gnuradio_extra_pin]
    - gnuradio-core {{ gnuradio_extra_pin }}.*  # [gnuradio_extra_pin]
    - libboost-headers
    - pip  # [win]
    - pybind11
    - python
    - fmt
    - spdlog

  run:
    - python

test:
  commands:
    # test that example flowgraphs compile
    {% set flowgraphs = ["rsp1a", "rsp1b", "rsp2", "rspduo_slave", "rspdx-LNA"] %}
    {% for flowgraph in flowgraphs %}
    - grcc $PREFIX/share/gr-{{ oot_name }}/examples/{{ flowgraph }}.grc  # [not win]
    - grcc %PREFIX%\\Library\\share\\gr-{{ oot_name }}\\examples\\{{ flowgraph }}.grc  # [win]
    {% endfor %}

    ## verify that (some) headers get installed
    - test -f $PREFIX/include/gnuradio/{{ oot_name }}/api.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\gnuradio\\{{ oot_name }}\\api.h exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]

    ## verify that (some) GRC blocks get installed
    {% set blocks = ["sdrplay3_rsp1", "sdrplay3_rsp1a", "sdrplay3_rsp1b", "sdrplay3_rsp2", "sdrplay3_rspduo", "sdrplay3_rspdx"] %}
    {% for block in blocks %}
    - test -f $PREFIX/share/gnuradio/grc/blocks/{{ block }}.block.yml  # [not win]
    - if not exist %PREFIX%\\Library\\share\\gnuradio\\grc\\blocks\\{{ block }}.block.yml exit 1  # [win]
    {% endfor %}

  imports:
    # verify that the python module imports
    - gnuradio.{{ oot_name }}

  requires:
    - gnuradio-grc
    - gnuradio-qtgui

about:
  home: https://github.com/fventuri/gr-sdrplay3
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Out-of-tree GNU Radio module for SDRplay RSP devices - SDRplay API V3.x"
  description: >
    GNU Radio OOT module for SDRplay RSP devices (SDRplay API V3.x)
    This OOT GNU Radio module supports the following SDRplay RSP devices:
      - RSP1
      - RSP1A
      - RSP1B
      - RSP2
      - RSPduo (all modes of operation)
      - RSPdx

    Example gnuradio-companion flowgraphs are installed with the package and
    can be found in:
        - (Linux/macOS) `$CONDA_PREFIX/share/gr-sdrplay3/examples`
        - (Windows) `%CONDA_PREFIX%\share\gr-sdrplay3\examples`
