name: CI

on: push

env:
  SDRPLAY_SOFTWARE_DOWNLOADS: 'https://www.sdrplay.com/software'

jobs:
  macos-test:
    name: MacOS test
    runs-on: macos-latest
    steps:
      - name: Check MacOS version
        run: sw_vers
      - name: Install prereqs
        run: brew install pybind11
      - name: Install GNU Radio
        run: brew install gnuradio
      - name: Install SDRplay API 3.X
        env:
          SDRPLAY_API_FILE_MACOS: SDRplayAPI-macos-installer-universal-3.15.0.pkg
        run: |
          curl -s -S -O "$SDRPLAY_SOFTWARE_DOWNLOADS/$SDRPLAY_API_FILE_MACOS"
          sudo installer -pkg "$SDRPLAY_API_FILE_MACOS" -target /
      - name: Check SDRplay API install
        run: |
          ls -l /usr/local/lib
          echo '--------------------------------------'
          otool -L /usr/local/lib/libsdrplay_api.so
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Check things before install
        run: |
          otool -L build/python/sdrplay3/bindings/sdrplay3_python.cpython-312-darwin.so
          echo '--------------------------------------'
          otool -l build/python/sdrplay3/bindings/sdrplay3_python.cpython-312-darwin.so | grep -B1 -A4 LC_RPATH
          echo '--------------------------------------'
          otool -L build/lib/libgnuradio-sdrplay3.g*.dylib
          echo '--------------------------------------'
          otool -l build/lib/libgnuradio-sdrplay3.g*.dylib | grep -B1 -A4 LC_RPATH
      - name: Install
        run: |
          cd build
          sudo make install
      - name: Check things after install
        run: |
          python -c 'from gnuradio import sdrplay3'
